development_defaults: &defaults
  adapter: mysql2
  host: 127.0.0.1
  username: root
  password:
  
development:
  <<: *defaults
  database: do_me_a_favor_dev

test:
  <<: *defaults
  database: do_me_a_favor_test
